module.exports = [
  ['Leave of Absence and Hiatus', 'Staff expecting an extended absence must submit an LOA and notify leadership. Leave exceeding six months is converted to Staff on Hiatus, which removes operational permissions until return. Leadership members on extended hiatus may be asked to step down temporarily or have an acting replacement appointed. Quality Control remains exempt from development activity expectations when no testing work is available.'],
  ['Welcome','Wes Evil Development develops Roblox experiences through accountable teamwork, documented work, constructive quality control, and a clear chain of command.'],
  ['Chain of Command','Director of Development → Secretary → Team Leads → Development Staff and Quality Control. Reports involving a position are sent to the next appropriate level.'],
  ['Activity and Quotas','Staff must log meaningful work and meet assigned quota periods. Staff should notify leadership before extended inactivity. QC is exempt when no testing work is available. Leave longer than six months may result in Staff on Hiatus status and temporary access restrictions.'],
  ['Development Logging','Significant changes must be logged. Developers must identify the project, summarize the work, provide evidence when available, and link the related Trello card. Another developer’s work may not be edited without permission.'],
  ['Quality Control','Completed work is passed to QC through a handoff. QC provides objective, constructive feedback and records approval, requested changes, or rejection. Testing information is confidential unless leadership authorizes release.'],
  ['Hiring','Applications are reviewed through screening, background check, interview, and decision stages. Applicants receive a privacy notice before submitting information. Decisions must be based on role-related, documented criteria.'],
  ['Background Checks','The Secretary or authorized leadership conducts background checks using the official WED template. Reviews cover subject information, relevant Roblox profile findings, Discord activity and profile review, verified infractions, evidence, outcome, and investigator certification. Only necessary, relevant information may be collected.'],
  ['Discipline','Verbal counseling remains the first step. Write-ups may be proposed by someone above the subject’s rank, but only the Secretary or Director of Development+ may approve them. Three approved write-ups trigger suspension and review. After return, one additional approved write-up may result in termination. Severe violations may be handled immediately.'],
  ['Confidentiality','Private channels, development discussions, unreleased content, repositories, documentation, internal tools, applications, background checks, disciplinary records, and leadership discussions may not be disclosed without authorization.'],
  ['Privacy and Security','WED collects only information needed for department operations, restricts access by role, records sensitive actions in an audit log, protects credentials in environment variables, uses encrypted transport in production, applies retention periods, and offers access, correction, export, and deletion request procedures.'],
];
